name: Pytest Cached

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8']
        pytorch_version: ['1.10.0']
        platform: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        jit_status: ['jit_disabled']




    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
       cache: 'pip'
       python-version: ${{ matrix.python_version }}

    - name: Install Nox dependencies
      shell: bash
      run: pip install -r requirements/requirements-nox.txt

    - name: Install libsndfile and libgomp1 on Ubuntu
      shell: bash
      run: sudo apt-get install -y libsndfile-dev libgomp1
      if: startsWith(runner.os, 'Linux') == true

    - name: Install libomp on macOS
      shell: bash
      run: brew install libomp
      if: startsWith(runner.os, 'macOS') == true

    - name: Run Nox session for brevitas pytest
      shell: bash
      run: nox -v -s tests_brevitas_cpu-${{ matrix.python_version }}\(${{ matrix.jit_status }}\,\ pytorch_${{ matrix.pytorch_version }}\)


